### ISSUE TITLE
N64 WiiU WIP Core Blog.

### ISSUE THREAD

**Issue by Ploggy** [Clownacy/clownmdemu-core#49]
I'm sorry to post this here since it has nothing to so with Clowndemu :P
I did leave a msg on your Blog bit it didn't display after I sent it?

I just want to thank you for looking into N64 for the WiiU. your Blog post was an interesting read. You seem to have gotten really far even getting the Core to compile and run something :)
While I'm less than useless when it comes to coding and things like that M4xw could have saved you some time debugging, he's the maintainer of the Retroarch Mupen64 Core :) 

How far are you planning on taking this N64 core? I see you primary goal is the OpenGL ES 2.0 renderer? 
but honestly I hope you can make the N64 Core a reality. We have a reasonable PS1 Core 90% of games are running perfectly fine but some are still under performing, I'm hoping the OpenGL ES 2.0 will help there if you continue your work.

I see your work on the Core is with Aroma in mind? Tho I think it should be able to work on the Tiramisu environment too (that's what Retroarch currently runs on)
You mention that the Retrorach port is going through a messy refactor (which is true) but the old Tiramisu Isn't broken, your Core should be able to run on that just fine.

I hope you continue your port, even just for the OpenGL ES 2.0 work, I know Gary is still working on his ANGLE port but the more the merrier :D 
M4xw is working on an aot recompiler that likely can be reworked to run on WiiU so if combined with your work could produce a working (fullspeed hopes) N64 Core for WiiU.

Again sorry for posting this here, I would have posted this on you Blog, but my last message didn't got through and you don't seem to be a member of GBAtemp and I couldn't find you on Discord.. I did find you on Sonic Retro but I couldn't send a PM :p
I'll delete this if its inappropriate.

Thank you for even looking into brining new (3D) Cores to WiiU. Its very much appreciated.

**Comment by Clownacy** [comment]
The blog requires that I approve each comment before they appear publicly. I've posted [a reply](https://clownacy.wordpress.com/2024/01/10/porting-a-nintendo-64-emulator-to-the-wii-u-at-1fps/comment-page-1/#comment-156) on the blog, but I'll cross-post it here too:

I have been taking a break from the project after being stumped on how to make GLideN64 work on big-endian platforms. My newest plan is to install big-endian Gentoo Linux on my Raspberry Pi 3B+, so that I have a big-endian platform with hardware-accelerated OpenGL support. With that, it should be trivial to get GLideN64 working properly. Once that is done, I can focus on making a proper OpenGLES2 implementation and finally get the emulator running at a decent speed on the Wii U.

**Comment by Ploggy** [comment]
I'm glad you are continuing to work on it and hope you can get the OpenGLES2 stuff working on WiiU, there's still quite a few of us hardcore WiiU Retroarch users still out there looking forward to what you can do.
N64 on WiiU is like the Holy Grail of RA Cores lol 

Thanks :)

I'll post this to your Blog too and mark this as closed :)
